// LOCALHOST
###
GET http://localhost:3000 HTTP/1.1
###
GET http://localhost:3000/contacts
###
GET http://localhost:3000/contacts/66f77d6c74ad0f43e4341169
###
GET http://localhost:3000/contacts/66f77d6c74ad0f43e434116a
###
GET http://localhost:3000/contacts/66f77d6c74ad0f43e434116b

// PRODUCTION Deploy
### 
GET https://node-web-services-w2.onrender.com HTTP/1.1
###
GET https://node-web-services-w2.onrender.com/contacts
###
GET https://node-web-services-w2.onrender.com/contacts/66f77d6c74ad0f43e4341169
###
GET https://node-web-services-w2.onrender.com/contacts/66f77d6c74ad0f43e434116a
###
GET https://node-web-services-w2.onrender.com/contacts/66f77d6c74ad0f43e434116b

